name: pfile
version: 1.0.1+1
homepage: https://github.com/SunnyApp/pfile
description: A flutter project for working with files/binary data in a cross-platform way
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  logging: ^1.0.0
  path_provider: ^2.0.1
  buffer: ^1.1.0
  uuid: ^3.0.1
  dartx: ^0.6.0
  chunked_stream: ^1.4.0
  flutter: 
    sdk: flutter
dev_dependencies: 
  pedantic: ^1.11.0
  sunny_dart: ^0.7.0+5
  flutter_test:
    sdk: flutter
